import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {expect,test,vi} from 'vitest';
import {PayComponentPage} from './PayComponentPage';
import {PayComponentApi,PayComponentVersion} from './pay-component-api';

const component:PayComponentVersion={identityId:'20000000-0000-0000-0000-000000000001',code:'BASIC',name:'Basic Pay',componentType:'EARNING',versionId:'21000000-0000-0000-0000-000000000001',versionSequence:1,versionNo:1,formulaType:'FIXED',formulaExpression:null,fixedAmount:50000,roundingScale:2,effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesVersionId:null,superseded:false};
function fakeApi(overrides:Partial<PayComponentApi>={}):PayComponentApi{return {list:vi.fn().mockResolvedValue([]),history:vi.fn().mockResolvedValue([component]),create:vi.fn().mockResolvedValue(component),addVersion:vi.fn().mockResolvedValue({...component,versionSequence:2,approvalStatus:'DRAFT'}),correct:vi.fn().mockResolvedValue({...component,versionSequence:2,approvalStatus:'DRAFT'}),endDate:vi.fn().mockResolvedValue({...component,effectiveTo:'2027-01-01',versionNo:2}),approve:vi.fn().mockResolvedValue({...component,approvalStatus:'APPROVED'}),...overrides}}

test('rejects the screen when component read is absent',()=>{const api=fakeApi();render(<PayComponentPage api={api} permissions={new Set()}/>);expect(screen.getByRole('alert')).toHaveTextContent('do not have permission');expect(api.list).not.toHaveBeenCalled()});
test('renders effective components and immutable history',async()=>{const api=fakeApi({list:vi.fn().mockResolvedValue([component])});render(<PayComponentPage api={api} permissions={new Set(['compensation.component.read'])}/>);fireEvent.click(await screen.findByRole('button',{name:/BASIC/}));expect(await screen.findByText('Version 1: fixed 50000')).toBeInTheDocument();expect(screen.getByText('2026-01-01 to open')).toBeInTheDocument()});
test('creates a fixed earning component draft',async()=>{const api=fakeApi();render(<PayComponentPage api={api} permissions={new Set(['compensation.component.read','compensation.component.create'])}/>);await screen.findByText('No approved pay components');fireEvent.change(screen.getByLabelText('Code'),{target:{value:'basic'}});fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Basic Pay'}});fireEvent.change(screen.getByLabelText('Fixed amount'),{target:{value:'50000'}});fireEvent.click(screen.getByRole('button',{name:'Create pay-component draft'}));await waitFor(()=>expect(api.create).toHaveBeenCalledWith(expect.objectContaining({code:'BASIC',componentType:'EARNING',formulaType:'FIXED',fixedAmount:50000,roundingScale:2})))});
test('exposes version and optimistic end-date workflows',async()=>{const api=fakeApi({list:vi.fn().mockResolvedValue([component])});render(<PayComponentPage api={api} permissions={new Set(['compensation.component.read','compensation.component.version.create','compensation.component.version.end-date'])}/>);fireEvent.click(await screen.findByRole('button',{name:/BASIC/}));await screen.findByText('Version 1: fixed 50000');fireEvent.change(screen.getByLabelText('Version Fixed amount'),{target:{value:'55000'}});fireEvent.change(screen.getByLabelText('Version effective from'),{target:{value:'2027-01-01'}});fireEvent.click(screen.getByRole('button',{name:'Add version'}));await waitFor(()=>expect(api.addVersion).toHaveBeenCalledWith(component.identityId,expect.objectContaining({fixedAmount:55000,effectiveFrom:'2027-01-01'})));fireEvent.change(screen.getByLabelText('End date'),{target:{value:'2027-01-01'}});fireEvent.click(screen.getByRole('button',{name:'End-date pay-component version'}));await waitFor(()=>expect(api.endDate).toHaveBeenCalledWith(component.identityId,component.versionId,component.versionNo,'2027-01-01'))});
test('surfaces API problem details accessibly',async()=>{const api=fakeApi({list:vi.fn().mockRejectedValue(new Error('Tenant context unavailable'))});render(<PayComponentPage api={api} permissions={new Set(['compensation.component.read'])}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Tenant context unavailable')});