import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {expect,test,vi} from 'vitest';
import {PayComponentVersion} from '../pay-component/pay-component-api';
import {PayrollBasePage} from './PayrollBasePage';
import {ComponentBaseMembership,PayrollBaseApi,PayrollBaseVersion} from './payroll-base-api';

const base:PayrollBaseVersion={identityId:'30000000-0000-0000-0000-000000000001',code:'REGULAR_GROSS',name:'Regular gross',lifecycleStatus:'ACTIVE',ownershipScope:'TENANT',countryCode:null,protectedFlag:false,confidentialityLevel:'STANDARD',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'31000000-0000-0000-0000-000000000001',versionSequence:1,versionNo:1,catalogueSchemaVersion:1,baseCategory:'CALCULATION',aggregationMethod:'SUM',description:'Regular earnings',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesVersionId:null,superseded:false};
const component:PayComponentVersion={identityId:'20000000-0000-0000-0000-000000000001',code:'BASIC',name:'Basic Pay',componentType:'EARNING',lifecycleStatus:'ACTIVE',ownershipScope:'TENANT',countryCode:null,protectedFlag:false,confidentialityLevel:'STANDARD',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'21000000-0000-0000-0000-000000000001',versionSequence:1,versionNo:1,catalogueSchemaVersion:1,classificationStatus:'COMPLETE',formulaType:'FIXED',formulaExpression:null,fixedAmount:50000,roundingScale:2,componentCategory:'CASH_EARNING',componentSubcategory:'BASIC_PAY',cashImpact:'INCREASE',payeeType:'EMPLOYEE',paymentChannel:'PAYROLL_BANK',settlementTiming:'CURRENT_PERIOD',payslipVisibility:'SHOW',zeroValueVisibility:'SUPPRESS',negativeValuePolicy:'PROHIBIT',frequency:'MONTHLY',valueNature:'FIXED',amountRepresentation:'MONTHLY_AMOUNT',taxTreatment:'DELEGATED',payrollTiming:'REGULAR',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesVersionId:null,superseded:false};
const membership:ComponentBaseMembership={membershipId:'32000000-0000-0000-0000-000000000001',payrollBaseId:base.identityId,payrollBaseVersionId:base.versionId,payrollBaseCode:base.code,payrollBaseVersionSequence:1,componentId:component.identityId,componentVersionId:component.versionId,componentCode:'BASIC',componentName:'Basic Pay',componentVersionSequence:1,membershipSequence:1,versionNo:1,membershipType:'INCLUDE',inclusionPercent:'100.00000000',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesMembershipId:null,superseded:false};
function fakeApi(overrides:Partial<PayrollBaseApi>={}):PayrollBaseApi{return {list:vi.fn().mockResolvedValue([]),history:vi.fn().mockResolvedValue([base]),create:vi.fn().mockResolvedValue(base),addVersion:vi.fn().mockResolvedValue({...base,approvalStatus:'DRAFT',versionSequence:2}),correct:vi.fn().mockResolvedValue({...base,approvalStatus:'DRAFT',versionSequence:2}),approve:vi.fn().mockResolvedValue(base),endDate:vi.fn().mockResolvedValue({...base,effectiveTo:'2027-01-01'}),retire:vi.fn().mockResolvedValue({...base,lifecycleStatus:'RETIRED'}),memberships:vi.fn().mockResolvedValue([membership]),createMembership:vi.fn().mockResolvedValue(membership),correctMembership:vi.fn().mockResolvedValue(membership),approveMembership:vi.fn().mockResolvedValue(membership),endDateMembership:vi.fn().mockResolvedValue({...membership,effectiveTo:'2027-01-01'}),components:vi.fn().mockResolvedValue([component]),...overrides};}

test('requires base read permission',()=>{const api=fakeApi();render(<PayrollBasePage api={api} permissions={new Set()}/>);expect(screen.getByRole('alert')).toHaveTextContent('do not have permission');expect(api.list).not.toHaveBeenCalled()});
test('renders exact membership decimal strings',async()=>{const api=fakeApi({list:vi.fn().mockResolvedValue([base])});render(<PayrollBasePage api={api} permissions={new Set(['compensation.base.read'])}/>);fireEvent.click(await screen.findByRole('button',{name:/REGULAR_GROSS/}));expect(await screen.findByText('100.00000000')).toBeInTheDocument();expect(screen.getByText('BASIC v1')).toBeInTheDocument()});
test('creates a base and exact component membership',async()=>{const api=fakeApi({list:vi.fn().mockResolvedValue([base])});render(<PayrollBasePage api={api} permissions={new Set(['compensation.base.read','compensation.base.membership.create'])}/>);fireEvent.click(await screen.findByRole('button',{name:/REGULAR_GROSS/}));await screen.findByText('100.00000000');fireEvent.change(screen.getByLabelText('Membership component version'),{target:{value:component.versionId}});fireEvent.click(screen.getByRole('button',{name:'Create membership draft'}));await waitFor(()=>expect(api.createMembership).toHaveBeenCalledWith(base.identityId,expect.objectContaining({payrollBaseVersionId:base.versionId,componentId:component.identityId,componentVersionId:component.versionId,inclusionPercent:'100.00000000'})))});
