import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {eligibilityFactTypes} from './salary-structure-api';
import type {CompensationConfigurationApi,EligibilityEvaluation,EligibilityOperator,EligibilityRuleCreate,EligibilityRuleVersion,EligibilityScalar} from './salary-structure-api';
export function EligibilityRulePanel({api,permissions,asOf}:{api:CompensationConfigurationApi;permissions:Set<string>;asOf:string}){
 const [items,setItems]=useState<EligibilityRuleVersion[]>([]);const [history,setHistory]=useState<EligibilityRuleVersion[]>([]);const [selected,setSelected]=useState<EligibilityRuleVersion|null>(null);const [facts,setFacts]=useState('{"COUNTRY_CODE":"IN"}');const [evaluation,setEvaluation]=useState<EligibilityEvaluation|null>(null);const [error,setError]=useState('');
 const canRead=permissions.has('compensation.eligibility-rule.read');
 useEffect(()=>{if(!canRead)return;void api.eligibilityList(asOf).then(setItems).catch(value=>setError((value as Error).message))},[api,asOf,canRead]);
 async function select(item:EligibilityRuleVersion){setSelected(item);setEvaluation(null);try{setHistory(await api.eligibilityHistory(item.identityId))}catch(value){setError((value as Error).message)}}
 async function create(input:EligibilityRuleCreate){try{await api.eligibilityCreate(input);setItems(await api.eligibilityList(asOf))}catch(value){setError((value as Error).message)}}
 async function approve(item:EligibilityRuleVersion){try{await api.eligibilityApprove(item.identityId,item.versionId);setHistory(await api.eligibilityHistory(item.identityId))}catch(value){setError((value as Error).message)}}
 async function evaluate(){if(!selected)return;setError('');try{const parsed=JSON.parse(facts) as Record<string,EligibilityScalar>;setEvaluation(await api.eligibilityEvaluate(selected.identityId,selected.versionId,parsed))}catch(value){setError((value as Error).message)}}
 if(!canRead)return <section className="configuration-panel"><h3>Eligibility rules</h3><p role="alert">You do not have permission to view eligibility rules.</p></section>;
 return <section className="configuration-panel" aria-labelledby="eligibility-panel-title"><div className="section-heading"><div><p className="eyebrow">Typed criteria</p><h3 id="eligibility-panel-title">Eligibility rules</h3></div><span className="count-badge">{items.length}</span></div>{error&&<p className="error" role="alert">{error}</p>}
  <div className="configuration-list">{items.length===0?<p>No approved eligibility rules effective on {asOf}.</p>:items.map(item=><button className="configuration-button" key={item.versionId} onClick={()=>void select(item)}><strong>{item.code}</strong><span>{item.name}</span><small>{item.criteria.length} conjunctive criteria</small></button>)}</div>
  {permissions.has('compensation.eligibility-rule.create')&&<RuleEditor submit={create}/>}
  {history.length>0&&<ol className="compact-timeline">{history.map(item=><li key={item.versionId}><span><strong>v{item.versionSequence} {item.name}</strong><small>{item.resultWhenMatched} / {item.resultWhenNotMatched}</small></span>{item.approvalStatus==='DRAFT'&&permissions.has('compensation.eligibility-rule.approve')&&<button onClick={()=>void approve(item)}>Approve eligibility rule</button>}</li>)}</ol>}
  {selected&&permissions.has('compensation.eligibility-rule.evaluate')&&<div className="panel-form"><h4>Synthetic design-time evaluation</h4><label>Synthetic eligibility facts<textarea aria-label="Synthetic eligibility facts" value={facts} onChange={event=>setFacts(event.target.value)}/></label><button onClick={()=>void evaluate()}>Evaluate synthetic facts</button>{evaluation&&<div className="evidence-card" role="status"><strong>Result: {evaluation.result}</strong><p>{evaluation.disclaimer}</p><code>{evaluation.evaluationHash}</code></div>}</div>}
 </section>;
}
function RuleEditor({submit}:{submit:(input:EligibilityRuleCreate)=>Promise<void>}){
 const [code,setCode]=useState('');const [name,setName]=useState('');const [factKey,setFactKey]=useState('COUNTRY_CODE');const [operator,setOperator]=useState<EligibilityOperator>('EQ');const [value,setValue]=useState('IN');const [effectiveFrom,setEffectiveFrom]=useState(new Date().toISOString().slice(0,10));const factType=eligibilityFactTypes[factKey];
 async function save(event:FormEvent){event.preventDefault();let expected:EligibilityScalar|EligibilityScalar[];if(operator==='IN'||operator==='NOT_IN')expected=value.split(',').map(item=>factType==='NUMBER'?Number(item.trim()):item.trim());else expected=factType==='NUMBER'?Number(value):value;await submit({code,version:{name,resultWhenMatched:'ELIGIBLE',resultWhenNotMatched:'NOT_ELIGIBLE',effectiveFrom,criteria:[{criterionSequence:1,factKey,factType,comparisonOperator:operator,value:expected}]}})}
 return <form className="panel-form" onSubmit={event=>void save(event)}><h4>Create rule draft</h4><label>Eligibility rule code<input required value={code} pattern="[A-Z][A-Z0-9_]{1,39}" onChange={event=>setCode(event.target.value.toUpperCase())}/></label><label>Eligibility rule name<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>Fact key<select value={factKey} onChange={event=>setFactKey(event.target.value)}>{Object.keys(eligibilityFactTypes).sort().map(key=><option key={key}>{key}</option>)}</select></label><label>Fact type<input value={factType} readOnly/></label><label>Operator<select value={operator} onChange={event=>setOperator(event.target.value as EligibilityOperator)}>{['EQ','NE','IN','NOT_IN','GTE','LTE'].map(item=><option key={item}>{item}</option>)}</select></label><label>Expected value<input required value={value} onChange={event=>setValue(event.target.value)}/></label><label>Rule effective from<input required type="date" value={effectiveFrom} onChange={event=>setEffectiveFrom(event.target.value)}/></label><button type="submit">Create eligibility-rule draft</button></form>;
}
