import {fireEvent,render,screen,waitFor} from '@testing-library/react';import {expect,test,vi} from 'vitest';import {EligibilityRulePanel} from './EligibilityRulePanel';
import type {CompensationConfigurationApi,CtcPolicyVersion,EligibilityRuleVersion,SalaryStructureValidation,SalaryStructureVersion} from './salary-structure-api';
export const component={identityId:'c1',versionId:'cv1',code:'BASIC',name:'Basic',componentType:'EARNING' as const,formulaType:'FIXED' as const,approvalStatus:'APPROVED' as const};
export const ctc:CtcPolicyVersion={identityId:'p1',code:'STD_CTC',lifecycleStatus:'ACTIVE',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'pv1',versionSequence:1,versionNo:0,name:'Standard CTC',currency:'INR',annualisationMethod:'MONTHLY_X_12',toleranceAmount:.01,residualComponentId:'c1',residualComponentVersionId:'cv1',residualComponentCode:'BASIC',residualComponentName:'Basic',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'DRAFT',supersedesVersionId:null,superseded:false,treatments:[]};
export const rule:EligibilityRuleVersion={identityId:'r1',code:'INDIA',lifecycleStatus:'ACTIVE',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'rv1',versionSequence:1,versionNo:0,name:'India rule',resultWhenMatched:'ELIGIBLE',resultWhenNotMatched:'NOT_ELIGIBLE',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesVersionId:null,superseded:false,criteria:[{id:'q1',criterionSequence:1,factKey:'COUNTRY_CODE',factType:'TEXT',comparisonOperator:'EQ',value:'IN',versionNo:0}]};
export const structure:SalaryStructureVersion={identityId:'s1',code:'DEFAULT',identityStatus:'ACTIVE',versionId:'sv1',versionSequence:1,versionNo:0,name:'Default',currency:'INR',structureSchemaVersion:1,structureType:'STANDARD',payFrequency:'MONTHLY',confidentialityLevel:'STANDARD',ctcPolicyVersionId:'pv1',eligibilityRuleVersionId:'rv1',targetType:'ANNUAL_CTC',targetAnnualAmount:1200000,toleranceAmount:.01,residualComponentVersionId:'cv1',configurationHash:'config',validationFingerprint:null,effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'DRAFT',supersedesVersionId:null,superseded:false,lines:[]};
export const validation:SalaryStructureValidation={validationId:'v1',identityId:'s1',versionId:'sv1',ctcPolicyVersionId:'pv1',eligibilityRuleVersionId:'rv1',effectiveDate:'2026-01-01',targetAmount:1200000,validationStatus:'PASS',requestHash:'request',configurationHash:'config',resultHash:'result',blockingErrorCount:0,warningCount:1,summary:{statutoryCompatibilityStatus:'STRUCTURAL_ONLY'},createdAt:'2026-01-01T00:00:00Z',createdBy:'maker',disclaimer:'DESIGN-TIME SALARY-STRUCTURE SIMULATION — NOT AN EMPLOYEE PAYROLL RESULT',lines:[]};
export function fakeApi(overrides:Partial<CompensationConfigurationApi>={}):CompensationConfigurationApi{return {listStructures:vi.fn().mockResolvedValue([structure]),listComponents:vi.fn().mockResolvedValue([component]),structureHistory:vi.fn().mockResolvedValue([structure]),createStructure:vi.fn().mockResolvedValue(structure),addStructureVersion:vi.fn().mockResolvedValue(structure),correctStructure:vi.fn().mockResolvedValue(structure),endDateStructure:vi.fn().mockResolvedValue(structure),approveStructure:vi.fn().mockResolvedValue(structure),simulateStructure:vi.fn().mockResolvedValue(validation),structureValidations:vi.fn().mockResolvedValue([]),bindStructureValidation:vi.fn().mockResolvedValue({...structure,validationFingerprint:'result'}),ctcList:vi.fn().mockResolvedValue([ctc]),ctcHistory:vi.fn().mockResolvedValue([ctc]),ctcCreate:vi.fn().mockResolvedValue(ctc),ctcAddVersion:vi.fn().mockResolvedValue(ctc),ctcCorrect:vi.fn().mockResolvedValue(ctc),ctcEndDate:vi.fn().mockResolvedValue(ctc),ctcApprove:vi.fn().mockResolvedValue({...ctc,approvalStatus:'APPROVED'}),ctcRetire:vi.fn().mockResolvedValue(ctc),eligibilityList:vi.fn().mockResolvedValue([rule]),eligibilityHistory:vi.fn().mockResolvedValue([rule]),eligibilityCreate:vi.fn().mockResolvedValue(rule),eligibilityAddVersion:vi.fn().mockResolvedValue(rule),eligibilityCorrect:vi.fn().mockResolvedValue(rule),eligibilityEndDate:vi.fn().mockResolvedValue(rule),eligibilityApprove:vi.fn().mockResolvedValue(rule),eligibilityEvaluate:vi.fn().mockResolvedValue({identityId:'r1',versionId:'rv1',result:'ELIGIBLE',matched:true,configurationHash:'c',factsHash:'f',evaluationHash:'e',disclaimer:'DESIGN-TIME ONLY',criteria:[]}),eligibilityRetire:vi.fn().mockResolvedValue(rule),...overrides}}

test('blocks eligibility reads without permission',()=>{const api=fakeApi();render(<EligibilityRulePanel api={api} permissions={new Set()} asOf="2026-01-01"/>);expect(screen.getByRole('alert')).toBeInTheDocument();expect(api.eligibilityList).not.toHaveBeenCalled()});
test('shows typed conjunctive rule history',async()=>{render(<EligibilityRulePanel api={fakeApi()} permissions={new Set(['compensation.eligibility-rule.read'])} asOf="2026-01-01"/>);fireEvent.click(await screen.findByRole('button',{name:/INDIA/}));expect(await screen.findByText(/v1 India rule/)).toBeInTheDocument()});
test('evaluates only synthetic supplied facts',async()=>{const api=fakeApi();render(<EligibilityRulePanel api={api} permissions={new Set(['compensation.eligibility-rule.read','compensation.eligibility-rule.evaluate'])} asOf="2026-01-01"/>);fireEvent.click(await screen.findByRole('button',{name:/INDIA/}));fireEvent.click(screen.getByRole('button',{name:'Evaluate synthetic facts'}));await waitFor(()=>expect(api.eligibilityEvaluate).toHaveBeenCalledWith('r1','rv1',{COUNTRY_CODE:'IN'}));expect(await screen.findByText('Result: ELIGIBLE')).toBeInTheDocument()});
test('uses V033 TEXT rather than STRING',async()=>{const api=fakeApi();render(<EligibilityRulePanel api={api} permissions={new Set(['compensation.eligibility-rule.read','compensation.eligibility-rule.create'])} asOf="2026-01-01"/>);fireEvent.change(screen.getByLabelText('Eligibility rule code'),{target:{value:'india'}});fireEvent.change(screen.getByLabelText('Eligibility rule name'),{target:{value:'India'}});fireEvent.click(screen.getByRole('button',{name:'Create eligibility-rule draft'}));await waitFor(()=>expect(api.eligibilityCreate).toHaveBeenCalledWith(expect.objectContaining({version:expect.objectContaining({criteria:[expect.objectContaining({factType:'TEXT'})]})})))});
test('rejects malformed synthetic JSON accessibly',async()=>{render(<EligibilityRulePanel api={fakeApi()} permissions={new Set(['compensation.eligibility-rule.read','compensation.eligibility-rule.evaluate'])} asOf="2026-01-01"/>);fireEvent.click(await screen.findByRole('button',{name:/INDIA/}));fireEvent.change(screen.getByLabelText('Synthetic eligibility facts'),{target:{value:'bad'}});fireEvent.click(screen.getByRole('button',{name:'Evaluate synthetic facts'}));expect(await screen.findByRole('alert')).toBeInTheDocument()});
