import {fireEvent,render,screen,waitFor} from '@testing-library/react';import {expect,test,vi} from 'vitest';import {SalaryStructureSimulationPanel} from './SalaryStructureSimulationPanel';
import type {CompensationConfigurationApi,CtcPolicyVersion,EligibilityRuleVersion,SalaryStructureValidation,SalaryStructureVersion} from './salary-structure-api';
export const component={identityId:'c1',versionId:'cv1',code:'BASIC',name:'Basic',componentType:'EARNING' as const,formulaType:'FIXED' as const,approvalStatus:'APPROVED' as const};
export const ctc:CtcPolicyVersion={identityId:'p1',code:'STD_CTC',lifecycleStatus:'ACTIVE',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'pv1',versionSequence:1,versionNo:0,name:'Standard CTC',currency:'INR',annualisationMethod:'MONTHLY_X_12',toleranceAmount:.01,residualComponentId:'c1',residualComponentVersionId:'cv1',residualComponentCode:'BASIC',residualComponentName:'Basic',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'DRAFT',supersedesVersionId:null,superseded:false,treatments:[]};
export const rule:EligibilityRuleVersion={identityId:'r1',code:'INDIA',lifecycleStatus:'ACTIVE',identityVersionNo:1,retirementEffectiveDate:null,retirementReason:null,retiredAt:null,retiredBy:null,versionId:'rv1',versionSequence:1,versionNo:0,name:'India rule',resultWhenMatched:'ELIGIBLE',resultWhenNotMatched:'NOT_ELIGIBLE',effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'APPROVED',supersedesVersionId:null,superseded:false,criteria:[{id:'q1',criterionSequence:1,factKey:'COUNTRY_CODE',factType:'TEXT',comparisonOperator:'EQ',value:'IN',versionNo:0}]};
export const structure:SalaryStructureVersion={identityId:'s1',code:'DEFAULT',identityStatus:'ACTIVE',versionId:'sv1',versionSequence:1,versionNo:0,name:'Default',currency:'INR',structureSchemaVersion:1,structureType:'STANDARD',payFrequency:'MONTHLY',confidentialityLevel:'STANDARD',ctcPolicyVersionId:'pv1',eligibilityRuleVersionId:'rv1',targetType:'ANNUAL_CTC',targetAnnualAmount:1200000,toleranceAmount:.01,residualComponentVersionId:'cv1',configurationHash:'config',validationFingerprint:null,effectiveFrom:'2026-01-01',effectiveTo:null,approvalStatus:'DRAFT',supersedesVersionId:null,superseded:false,lines:[]};
export const validation:SalaryStructureValidation={validationId:'v1',identityId:'s1',versionId:'sv1',ctcPolicyVersionId:'pv1',eligibilityRuleVersionId:'rv1',effectiveDate:'2026-01-01',targetAmount:1200000,validationStatus:'PASS',requestHash:'request',configurationHash:'config',resultHash:'result',blockingErrorCount:0,warningCount:1,summary:{statutoryCompatibilityStatus:'STRUCTURAL_ONLY'},createdAt:'2026-01-01T00:00:00Z',createdBy:'maker',disclaimer:'DESIGN-TIME SALARY-STRUCTURE SIMULATION — NOT AN EMPLOYEE PAYROLL RESULT',lines:[]};
export function fakeApi(overrides:Partial<CompensationConfigurationApi>={}):CompensationConfigurationApi{return {listStructures:vi.fn().mockResolvedValue([structure]),listComponents:vi.fn().mockResolvedValue([component]),structureHistory:vi.fn().mockResolvedValue([structure]),createStructure:vi.fn().mockResolvedValue(structure),addStructureVersion:vi.fn().mockResolvedValue(structure),correctStructure:vi.fn().mockResolvedValue(structure),endDateStructure:vi.fn().mockResolvedValue(structure),approveStructure:vi.fn().mockResolvedValue(structure),simulateStructure:vi.fn().mockResolvedValue(validation),structureValidations:vi.fn().mockResolvedValue([]),bindStructureValidation:vi.fn().mockResolvedValue({...structure,validationFingerprint:'result'}),ctcList:vi.fn().mockResolvedValue([ctc]),ctcHistory:vi.fn().mockResolvedValue([ctc]),ctcCreate:vi.fn().mockResolvedValue(ctc),ctcAddVersion:vi.fn().mockResolvedValue(ctc),ctcCorrect:vi.fn().mockResolvedValue(ctc),ctcEndDate:vi.fn().mockResolvedValue(ctc),ctcApprove:vi.fn().mockResolvedValue({...ctc,approvalStatus:'APPROVED'}),ctcRetire:vi.fn().mockResolvedValue(ctc),eligibilityList:vi.fn().mockResolvedValue([rule]),eligibilityHistory:vi.fn().mockResolvedValue([rule]),eligibilityCreate:vi.fn().mockResolvedValue(rule),eligibilityAddVersion:vi.fn().mockResolvedValue(rule),eligibilityCorrect:vi.fn().mockResolvedValue(rule),eligibilityEndDate:vi.fn().mockResolvedValue(rule),eligibilityApprove:vi.fn().mockResolvedValue(rule),eligibilityEvaluate:vi.fn().mockResolvedValue({identityId:'r1',versionId:'rv1',result:'ELIGIBLE',matched:true,configurationHash:'c',factsHash:'f',evaluationHash:'e',disclaimer:'DESIGN-TIME ONLY',criteria:[]}),eligibilityRetire:vi.fn().mockResolvedValue(rule),...overrides}}

test('shows explicit non-payroll boundary',async()=>{render(<SalaryStructureSimulationPanel api={fakeApi()} permissions={new Set(['compensation.structure.simulate'])} structure={structure}/>);expect(screen.getByText('DESIGN-TIME SIMULATION — NOT AN OFFICIAL PAYROLL RESULT')).toBeInTheDocument()});
test('runs deterministic simulation with supplied facts',async()=>{const api=fakeApi();render(<SalaryStructureSimulationPanel api={api} permissions={new Set(['compensation.structure.simulate'])} structure={structure}/>);fireEvent.click(screen.getByRole('button',{name:'Run design-time simulation'}));await waitFor(()=>expect(api.simulateStructure).toHaveBeenCalledWith('s1','sv1',expect.any(String),{COUNTRY_CODE:'IN'}));expect(await screen.findByText('PASS')).toBeInTheDocument()});
test('binds passing evidence only with bind permission',async()=>{const api=fakeApi({structureValidations:vi.fn().mockResolvedValue([validation])});render(<SalaryStructureSimulationPanel api={api} permissions={new Set(['compensation.structure.simulate','compensation.structure.validation.bind'])} structure={structure}/>);fireEvent.click(await screen.findByRole('button',{name:'Bind passing validation'}));await waitFor(()=>expect(api.bindStructureValidation).toHaveBeenCalledWith('s1','sv1','v1',0))});
test('does not expose binding to simulation-only users',async()=>{render(<SalaryStructureSimulationPanel api={fakeApi({structureValidations:vi.fn().mockResolvedValue([validation])})} permissions={new Set(['compensation.structure.simulate'])} structure={structure}/>);expect(await screen.findByText(/NOT AN EMPLOYEE PAYROLL RESULT/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Bind passing validation'})).not.toBeInTheDocument()});
test('surfaces invalid facts without persisting evidence',async()=>{render(<SalaryStructureSimulationPanel api={fakeApi()} permissions={new Set(['compensation.structure.simulate'])} structure={structure}/>);fireEvent.change(screen.getByLabelText('Simulation eligibility facts'),{target:{value:'bad'}});fireEvent.click(screen.getByRole('button',{name:'Run design-time simulation'}));expect(await screen.findByRole('alert')).toBeInTheDocument()});
