import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import type {CompensationConfigurationApi,EligibilityScalar,SalaryStructureValidation,SalaryStructureVersion} from './salary-structure-api';
const requiredDisclaimer='DESIGN-TIME SIMULATION — NOT AN OFFICIAL PAYROLL RESULT';
export function SalaryStructureSimulationPanel({api,permissions,structure}:{api:CompensationConfigurationApi;permissions:Set<string>;structure:SalaryStructureVersion}){
 const [effectiveDate,setEffectiveDate]=useState(new Date().toISOString().slice(0,10));const [facts,setFacts]=useState('{"COUNTRY_CODE":"IN"}');const [evidence,setEvidence]=useState<SalaryStructureValidation[]>([]);const [error,setError]=useState('');
 useEffect(()=>{void api.structureValidations(structure.identityId,structure.versionId).then(setEvidence).catch(value=>setError((value as Error).message))},[api,structure.identityId,structure.versionId]);
 async function simulate(event:FormEvent){event.preventDefault();setError('');try{const eligibilityFacts=JSON.parse(facts) as Record<string,EligibilityScalar>;const result=await api.simulateStructure(structure.identityId,structure.versionId,effectiveDate,eligibilityFacts);setEvidence(current=>[result,...current.filter(value=>value.validationId!==result.validationId)])}catch(value){setError((value as Error).message)}}
 async function bind(item:SalaryStructureValidation){setError('');try{await api.bindStructureValidation(structure.identityId,structure.versionId,item.validationId,structure.versionNo)}catch(value){setError((value as Error).message)}}
 if(!permissions.has('compensation.structure.simulate'))return <section className="configuration-panel"><h3>Simulation evidence</h3><p className="permission-note">Design-time simulation requires <code>compensation.structure.simulate</code>.</p></section>;
 return <section className="configuration-panel" aria-labelledby="simulation-panel-title"><div className="section-heading"><div><p className="eyebrow">Immutable evidence</p><h3 id="simulation-panel-title">Salary-structure simulation</h3></div></div><p className="simulation-disclaimer">{requiredDisclaimer}</p>{error&&<p className="error" role="alert">{error}</p>}
  <form className="panel-form" onSubmit={event=>void simulate(event)}><label>Simulation effective date<input required type="date" value={effectiveDate} onChange={event=>setEffectiveDate(event.target.value)}/></label><label>Simulation eligibility facts<textarea aria-label="Simulation eligibility facts" value={facts} onChange={event=>setFacts(event.target.value)}/></label><button type="submit">Run design-time simulation</button></form>
  <div className="evidence-list">{evidence.length===0?<p>No validation evidence for this exact structure version.</p>:evidence.map(item=><article className="evidence-card" key={item.validationId}><div className="section-heading"><strong>{item.validationStatus}</strong><span>{item.blockingErrorCount} blockers · {item.warningCount} warnings</span></div><p>{item.disclaimer}</p><dl className="hash-grid"><dt>Request</dt><dd><code>{item.requestHash}</code></dd><dt>Configuration</dt><dd><code>{item.configurationHash}</code></dd><dt>Result</dt><dd><code>{item.resultHash}</code></dd></dl>{item.validationStatus==='PASS'&&permissions.has('compensation.structure.validation.bind')&&<button onClick={()=>void bind(item)}>Bind passing validation</button>}</article>)}</div>
 </section>;
}
